import { contextBridge, ipcRenderer } from "electron";
import type {
  CreateItemRequest,
  ArchiveCreateRequest,
  ArchiveExtractRequest,
  ArchiveListRequest,
  ArchivePreviewRequest,
  BatchRenameRequest,
  DeleteRequest,
  FileOperationRequest,
  FolderSyncRequest,
  HashRequest,
  PathSuggestionRequest,
  QuickLaunchRunRequest,
  RenameRequest,
  SearchOptions,
  SpaceApi,
  SvnCommandRequest,
  SystemContextMenuRequest,
  WorkspaceDocument
} from "../src/shared.js";

const api: SpaceApi = {
  bootstrap: () => ipcRenderer.invoke("space:bootstrap"),
  listDirectory: (path: string) => ipcRenderer.invoke("space:list-directory", path),
  searchFiles: (options: SearchOptions) => ipcRenderer.invoke("space:search-files", options),
  suggestPaths: (request: PathSuggestionRequest) => ipcRenderer.invoke("space:suggest-paths", request),
  createFolder: (request: CreateItemRequest) => ipcRenderer.invoke("space:create-folder", request),
  createFile: (request: CreateItemRequest) => ipcRenderer.invoke("space:create-file", request),
  renameItem: (request: RenameRequest) => ipcRenderer.invoke("space:rename-item", request),
  deleteItems: (request: DeleteRequest) => ipcRenderer.invoke("space:delete-items", request),
  copyItems: (request: FileOperationRequest) => ipcRenderer.invoke("space:copy-items", request),
  moveItems: (request: FileOperationRequest) => ipcRenderer.invoke("space:move-items", request),
  preview: (path: string) => ipcRenderer.invoke("space:preview", path),
  calculateHash: (request: HashRequest) => ipcRenderer.invoke("space:calculate-hash", request),
  previewBatchRename: (request: BatchRenameRequest) => ipcRenderer.invoke("space:preview-batch-rename", request),
  applyBatchRename: (request: BatchRenameRequest) => ipcRenderer.invoke("space:apply-batch-rename", request),
  previewFolderSync: (request: FolderSyncRequest) => ipcRenderer.invoke("space:preview-folder-sync", request),
  applyFolderSync: (request: FolderSyncRequest) => ipcRenderer.invoke("space:apply-folder-sync", request),
  listArchive: (request: ArchiveListRequest) => ipcRenderer.invoke("space:list-archive", request),
  previewArchiveEntry: (request: ArchivePreviewRequest) => ipcRenderer.invoke("space:preview-archive-entry", request),
  extractArchive: (request: ArchiveExtractRequest) => ipcRenderer.invoke("space:extract-archive", request),
  createArchive: (request: ArchiveCreateRequest) => ipcRenderer.invoke("space:create-archive", request),
  openPath: (path: string) => ipcRenderer.invoke("space:open-path", path),
  revealPath: (path: string) => ipcRenderer.invoke("space:reveal-path", path),
  openTerminal: (path: string) => ipcRenderer.invoke("space:open-terminal", path),
  copyTextToClipboard: (text: string) => ipcRenderer.invoke("space:copy-text-to-clipboard", text),
  runQuickLaunch: (request: QuickLaunchRunRequest) => ipcRenderer.invoke("space:run-quick-launch", request),
  runSvnCommand: (request: SvnCommandRequest) => ipcRenderer.invoke("space:svn-command", request),
  showSystemContextMenu: (request: SystemContextMenuRequest) => ipcRenderer.invoke("space:show-system-context-menu", request),
  getWorkspace: () => ipcRenderer.invoke("space:get-workspace"),
  saveWorkspace: (snapshot: WorkspaceDocument) => ipcRenderer.invoke("space:save-workspace", snapshot),
  minimizeWindow: () => ipcRenderer.invoke("space:window-minimize"),
  toggleMaximizeWindow: () => ipcRenderer.invoke("space:window-toggle-maximize"),
  closeWindow: () => ipcRenderer.invoke("space:window-close")
};

contextBridge.exposeInMainWorld("spaceAPI", api);
